# Generated by Django 5.1.7 on 2025-04-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='video',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
